FROM nginx:stable-alpine
RUN apk add --no-cache certbot certbot-nginx
COPY s_locator.conf /etc/nginx/conf.d/default.conf
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 80 443
ENTRYPOINT ["/entrypoint.sh"]