FROM nginx:stable-alpine
# Install Certbot and its Nginx plugin
RUN apk add --no-cache certbot certbot-nginx

COPY s_locator.conf /etc/nginx/conf.d/default.conf

# Copy entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 80 443
ENTRYPOINT ["/entrypoint.sh"]
# CMD ["tail", "-f", "/dev/null"]